In [ ]:
##Vegobjekt 915: Vegsystem i Trøndelag

In [402]:



import requests

params = {
'inkluder':'egenskaper,lokasjon',
'srid':'5973',
'segmentering':'false',
'trafikantgruppe':'K',#kjørende
'fylke':50,
'endret_etter':'2018-01-01T12:13:01',
'antall':200,
'start':'1002101974:0'#'0:0'
}

jwt_token = 'eyJ0eXAiOiJKV1QiLCJraWQiOiJITUNDTDd0ei93dWZja3ArcGVldUN0bmpyVms9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIyMjA0OTEzOTExMyIsImN0cyI6Ik9BVVRIMl9TVEFURUxFU1NfR1JBTlQiLCJhdXRoX2xldmVsIjo0MCwiYXVkaXRUcmFja2luZ0lkIjoiZjAwZDM1ODctZjYyNC00ZjY1LWI0YWUtMDQ3YzY1OTZjZDg1LTE4MDk3NzQ5MSIsInN1Ym5hbWUiOiIyMjA0OTEzOTExMyIsImlzcyI6Imh0dHBzOi8vd3d3LnZlZ3Zlc2VuLm5vOjQ0My9vcGVuYW0vb2F1dGgyL3JlYWxtcy9yb290L3JlYWxtcy9ub3JnZS5ubyIsInRva2VuTmFtZSI6ImFjY2Vzc190b2tlbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJhdXRoR3JhbnRJZCI6IktObkVxN1ZDT3hBbjdBTnVGejNGX2hlampWMCIsIm5vbmNlIjoiQVhGSUgyMTJ0UEdFcVRtWEJycUFOUFZwbGsxS3F5djIiLCJhdWQiOlsiMzc4YWMzOWItMTgwZC00M2VhLTllYzQtM2Y4NTg1NWRkOTAzIiwiaHR0cHM6Ly9hcGkudmVndmVzZW4ubm8iLCJodHRwczovL3d3dy52ZWd2ZXNlbi5ubzo0NDMvb3BlbmFtL29hdXRoMi9yZWFsbXMvcm9vdC9yZWFsbXMvbm9yZ2Uubm8iXSwibmJmIjoxNzczNzczNDEzLCJncmFudF90eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwic2NvcGUiOlsib3BlbmlkIiwic3Z2cGFydG5lcnByb2ZpbGUiXSwiYXV0aF90aW1lIjoxNzczNzczNDA5LCJyZWFsbSI6Ii9ub3JnZS5ubyIsImV4cCI6MTc3MzgwMjIxMywiaWF0IjoxNzczNzczNDEzLCJleHBpcmVzX2luIjoyODgwMCwianRpIjoiWkxDOHJtbU50Qi1TMVhWWlNsS0MwY1ZELUdNIiwiYWNyIjoiTGV2ZWw0IiwibmFtZSI6IkZOUiBkZXRlY3RlZCIsImdpdmVuX25hbWUiOiJGTlIgZGV0ZWN0ZWQiLCJmYW1pbHlfbmFtZSI6IkZOUiBkZXRlY3RlZCIsIm1heV9hY3QiOnsiY2xpZW50X2lkIjpbIk9BdXRoMl9BUElHV19Ub2tlblRyYW5zIiwiT0F1dGgyX2lhbWlkZW50aXR5YnJpZGdlIl19fQ.kBjx_kITljsKpMFWNwfei2rR-3wXtTT_P1TYagye2y35nCMntRg7q1KLFz4wmPPdzD9nSM3zvGHUPjTkDi3xv5rU_9Ob-OkNIkCnByw5BWKh_NDJky_UiJoZlWcXRlfcG8ap_tz4IrwkPK4hNAPFLi2T2jDPM0HmD75UrZ6iQNzTrXmVkw6hM_RSMU661qk0_MI18ImAJAUOwP2_LqwRo0GPKkbEVPCU_JP2AG4OdkU8qJEv53wANXlU0ediz6vpduoVS8mlBC56JRipnCmiGLhgCZc3sl0pvdruLyRDooastjUKpjD8T34LZFmXM01ZJ1GHF3H_6tgXH1nmLjjquDOS4VdDkk43NCcJCg3ClTbwUOArVkQ4H-O_q4CNfjv7wcggJf-WeZ73wkMEms_3hBRnYtV7PSxPH_cPRhfmTgFJznS706nt6M6wCvdAOomvLxJ4RbpT0a4HM87kfThTo-zrIKzBIpPsEVXZjF1MMVwQhN_TsukUp74fL15mu_ox'

headers = {
 'Authorization': f'Bearer {jwt_token}',
 'X-Client': 'vj_case'
}

with requests.get("https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915",params = params, headers = headers) as response:
    print(response)

<Response [200]>

In [409]:
response.json()['objekter'][0]

s = set()

for i in response.json()['objekter']:
    for j in i.keys():
        s.add(j)
        try:
            for k in i[j].keys():
                s.add(k)
        except:
            pass

In [410]:
s

{'adresser',
 'egenskaper',
 'fylker',
 'geometri',
 'href',
 'id',
 'kommuner',
 'kontraktsområder',
 'lengde',
 'lokasjon',
 'riksvegruter',
 'stedfestinger',
 'vegforvaltere',
 'vegsystemreferanser'}

In [1]:
import mysql.connector



def get_connector(database = None)-> mysql.connector:
    try:
        mydb = mysql.connector.connect(
          host = "localhost",
          user = "case_user",
          password = "password",
          database = database # Optional: connect to a specific database directly
        )
        print("Connection successful!")
        return mydb
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        return None

mydb = get_connector()
mydb_cursor = mydb.cursor()



# mydb_cursor.fetchall()#("CREATE DATABASE case")
mydb_cursor.execute("SHOW DATABASES")
mydb_cursor_ = mydb_cursor.fetchall()
mydb_cursor_

Connection successful!

[('case',),
 ('case2',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sys',)]

In [571]:
tables = ['vegobjekt_riksvegruter','vegobjekt_adresser','vegobjekt_vegforvaltere','vegobjekt_kontraktsomraader','vegobjekt_stedfesting','vegobjekt_vegsystemreferanse','vegobjekt_lokasjon_kommuner','vegobjekt_egenskap','vegobjekt_lokasjon','vegobjekt']
for t in tables:
    try:
        mydb_cursor.execute(f"DELETE FROM {t}")
    except:
        pass
    try:
        mydb_cursor.execute(f"DROP TABLE {t}")
        print(mydb_cursor.fetchall())
    except:
        pass

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

In [572]:
resp_json = response.json()



mydb = get_connector("case2")
mydb_cursor = mydb.cursor()



create_vegobjekt = """CREATE TABLE vegobjekt (
                    id BIGINT PRIMARY KEY,
                    href TEXT
                );"""
    
mydb_cursor.execute(create_vegobjekt)
print(mydb_cursor.fetchall())

create_vegobjekt_egenskap = """CREATE TABLE vegobjekt_egenskap (
                            
                            vegobjekt_id BIGINT ,
                            egenskap_id INT,
                            navn VARCHAR(100),
                            verdi_text TEXT,
                            verdi_int INT,
                            enum_id INT,
                            egenskapstype VARCHAR(50),
                            
                            PRIMARY KEY (vegobjekt_id, egenskap_id),
                            FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                        );"""

mydb_cursor.execute(create_vegobjekt_egenskap)
print(mydb_cursor.fetchall())

create_vegobjekt_lokasjon = """CREATE TABLE vegobjekt_lokasjon (
                            id SERIAL PRIMARY KEY,
                            vegobjekt_id BIGINT,
                            lengde DOUBLE,
                            FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                        );"""

mydb_cursor.execute(create_vegobjekt_lokasjon)
print(mydb_cursor.fetchall())

create_vegobjekt_kommune = """CREATE TABLE vegobjekt_lokasjon_kommuner (
                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                kommune INT,
                                vegobjekt_id BIGINT,
                                PRIMARY KEY (lokasjon_id, kommune),
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""

mydb_cursor.execute(create_vegobjekt_kommune)
print(mydb_cursor.fetchall())

create_vegobjekt_vegsystemreferanse = """CREATE TABLE vegobjekt_vegsystemreferanse (
                            id SERIAL PRIMARY KEY,
                            lokasjon_id INT REFERENCES vegobjekt_lokasjon(id), 
                        
                            vegkategori CHAR(1),
                            fase CHAR(1),
                            vegnummer INT,
                        
                            strekning INT,
                            delstrekning INT,
                            arm BOOLEAN,
                            adskilte_lop VARCHAR(10),
                            trafikantgruppe CHAR(1),
                            retning VARCHAR(10),
                            fra_meter DOUBLE,
                            til_meter DOUBLE,
                        
                            metrert_retning VARCHAR(10),
                        
                            kortform VARCHAR(50),
                            
                            vegobjekt_id BIGINT,
                            FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            
                        );"""

mydb_cursor.execute(create_vegobjekt_vegsystemreferanse)
print(mydb_cursor.fetchall())

create_vegobjekt_stedfesting = """CREATE TABLE vegobjekt_stedfesting (
                                id SERIAL PRIMARY KEY,
                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                            
                                type VARCHAR(20),
                                veglenkesekvensid BIGINT ,
                                startposisjon DOUBLE,
                                sluttposisjon DOUBLE,
                                retning VARCHAR(10),
                                kortform VARCHAR(50),
                                
                                vegobjekt_id BIGINT,
                                UNIQUE (veglenkesekvensid)
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""

mydb_cursor.execute(create_vegobjekt_stedfesting)
print(mydb_cursor.fetchall())

create_vegobjekt_kontraktsomraader = """CREATE TABLE vegobjekt_kontraktsomraader (
                                id BIGINT ,
                                nummer INT,
                                navn varchar(100),

                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                vegobjekt_id BIGINT,
                                PRIMARY KEY (id,vegobjekt_id),
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""

mydb_cursor.execute(create_vegobjekt_kontraktsomraader)
print(mydb_cursor.fetchall())


create_vegobjekt_vegforvaltere = """CREATE TABLE vegobjekt_vegforvaltere (
                                enumid INT,
                                vegforvalter varchar(50),

                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                vegobjekt_id BIGINT,
                                PRIMARY KEY (enumid,vegobjekt_id),
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""


mydb_cursor.execute(create_vegobjekt_vegforvaltere)
print(mydb_cursor.fetchall())


create_vegobjekt_adresser = """CREATE TABLE vegobjekt_adresser (
                                navn VARCHAR(50),
                                adressekode INT,
                                
                                
                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                vegobjekt_id BIGINT,
                                
                                PRIMARY KEY (navn,adressekode),

                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""

mydb_cursor.execute(create_vegobjekt_adresser)
print(mydb_cursor.fetchall())


create_vegobjekt_riksvegrute = """CREATE TABLE vegobjekt_riksvegruter (
                                enumid INT,
                                riksvegrute varchar(100),
                                
                                
                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                vegobjekt_id BIGINT,
                                PRIMARY KEY (enumid,vegobjekt_id),
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""


mydb_cursor.execute(create_vegobjekt_riksvegrute)
print(mydb_cursor.fetchall())

Connection successful!
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

In [573]:


def insert_vegobjekt(mydb_cursor, data):

    sql = """
    INSERT INTO vegobjekt (
        id,
        href
    )
    VALUES (%s, %s)
    """

    
    values = (
        data.get("id"),
        data.get("href")
    )

    mydb_cursor.execute(sql, values)
    mydb.commit()

    
    

def insert_vegobjekt_egenskap(mydb_cursor, egenskaper,vegobjekt_id):
                                
    sql = """
    INSERT INTO vegobjekt_egenskap (
        vegobjekt_id,
        egenskap_id,
        navn,
        verdi_text,
        verdi_int,
        enum_id,
        egenskapstype
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s)
    """
    mydb_cursor = mydb.cursor()
    for egenskap in egenskaper:
        if egenskap["egenskapstype"] == 'Heltall':
            values = (
                vegobjekt_id,
                egenskap.get("id"),
                egenskap.get("navn"),
                None,
                egenskap.get("verdi"),
                egenskap.get('enum_id'),
                egenskap.get("egenskapstype"),
            )
        else:
            values = (
                vegobjekt_id,
                egenskap.get("id"),
                egenskap.get("navn"),
                egenskap.get("verdi"),
                None,
                egenskap.get('enum_id'),
                egenskap.get("egenskapstype"),
            )
    
        mydb_cursor.execute(sql, values)
        mydb.commit()

    mydb_cursor.close()


def insert_vegobjekt_lokasjon(mydb_cursor, data,vegobjekt_id):

    sql = """
    INSERT INTO vegobjekt_lokasjon (
        vegobjekt_id,
        lengde
    )
    VALUES (%s, %s)
    """
    mydb_cursor = mydb.cursor()
    
    values = (
        vegobjekt_id,
        data.get("lengde"),
    )

    mydb_cursor.execute(sql, values)
    mydb.commit()

    mydb_cursor.execute('SELECT LAST_INSERT_ID()')
    lokasjon_id = mydb_cursor.fetchone()[0]
    
    mydb_cursor.close()
    
    insert_vegobjekt_kommuner(mydb, data,lokasjon_id,vegobjekt_id)
    
    insert_vegobjekt_vegsystemreferanse(mydb, data,lokasjon_id,vegobjekt_id)
    
    insert_vegobjekt_stedfesting(mydb, data,lokasjon_id,vegobjekt_id)


    if data.get('kontraktsområder'):
        insert_vegobjekt_kontraktsomraader(mydb, data,lokasjon_id,vegobjekt_id)

    if data.get('vegforvaltere'):
        insert_vegobjekt_vegforvaltere(mydb, data,lokasjon_id,vegobjekt_id)
    if data.get('riksvegruter'):
        insert_vegobjekt_riksvegruter(mydb, data,lokasjon_id,vegobjekt_id)
# for e in objekter[0]['egenskaper']:
#     insert_vegobjekt_egenskap(mydb,e,objekter[0]['id'])
# insert_vegobjekt_lokasjon(mydb,objekter[0]['lokasjon'],objekter[0]['id'])


def insert_vegobjekt_kommuner(mydb_cursor,data,lokasjon_id,vegobjekt_id):

    sql = """
    INSERT INTO vegobjekt_lokasjon_kommuner (
        lokasjon_id,
        kommune,
        vegobjekt_id
    )
    VALUES (%s, %s, %s)
    """
    
    mydb_cursor = mydb.cursor()
    for kommune in data['kommuner']:
        values = (
            lokasjon_id,
            kommune,
            vegobjekt_id,
        )

        mydb_cursor.execute(sql, values)
        mydb.commit()
    mydb_cursor.close()

def insert_vegobjekt_vegsystemreferanse(mydb_cursor, data,lokasjon_id,vegobjekt_id):

    mydb_cursor = mydb.cursor()
    # mydb_cursor.execute('SELECT LAST_INSERT_ID()')
    # lokasjon_id = mydb_cursor.fetchone()[0]


    sql = """
    INSERT INTO vegobjekt_vegsystemreferanse (
        lokasjon_id,
        vegkategori,
        fase,
        vegnummer,
        
        strekning,
        delstrekning,
        arm,
        adskilte_lop,
        trafikantgruppe,
        retning,
        fra_meter,
        til_meter,
        
        metrert_retning,
        
        kortform,
        vegobjekt_id
        
    )
    VALUES (%s, %s,%s,%s,%s,%s,%s,%s,%s, %s,%s,%s,%s,%s,%s)
    """

    
    for veg_ref in data['vegsystemreferanser']:
        vegsystem = veg_ref['vegsystem']
        strekning = veg_ref['strekning']
        values = (
            lokasjon_id,
            vegsystem.get("vegkategori"),
            vegsystem.get("fase"),
            vegsystem.get("nummer"),
            strekning.get('strekning'),
            strekning.get('delstrekning'),
            strekning.get('arm'),
            strekning.get('adskilte_løp'),
            strekning.get('trafikantgruppe'),
            strekning.get('retning'),
            strekning.get('fra_meter'),
            strekning.get('til_meter'),
            veg_ref['metrertLokasjon'].get('retning'),
            veg_ref.get('kortform'),
            vegobjekt_id
        )

    
        mydb_cursor.execute(sql, values)
        
    mydb.commit()

    mydb_cursor.close()


# insert_vegobjekt_lokasjon(mydb,objekter[0]['lokasjon'],objekter[0]['id'])

def insert_vegobjekt_stedfesting(mydb_cursor, data,lokasjon_id,vegobjekt_id):

    mydb_cursor = mydb.cursor()
    # mydb_cursor.execute('SELECT LAST_INSERT_ID()')
    # last_id = mydb_cursor.fetchone()[0]

    sql = """
    INSERT INTO vegobjekt_stedfesting (
        lokasjon_id,
        
        type,
        veglenkesekvensid,
        startposisjon,
        sluttposisjon,
        retning,
        kortform,
        
        vegobjekt_id  
    )
    VALUES (%s, %s,%s,%s,%s,%s,%s,%s)
    """

    
    stedfestinger = data['stedfestinger']
    for sted in stedfestinger:
        
        values = (
            lokasjon_id,
            sted.get('type'),
            sted.get("veglenkesekvensid"),
            sted.get("startposisjon"),
            sted.get('sluttposisjon'),
            sted.get('retning'),
            sted.get('kortform'),
            vegobjekt_id
        )

    
        mydb_cursor.execute(sql, values)
        
        mydb.commit()

    mydb_cursor.close()



def insert_vegobjekt_kontraktsomraader(mydb_cursor, data,lokasjon_id,vegobjekt_id):

    mydb_cursor = mydb.cursor()

    sql = """
    INSERT INTO vegobjekt_kontraktsomraader (
        id,
        nummer,
        navn,
        lokasjon_id,
        vegobjekt_id
    
    )
    VALUES (%s, %s,%s,%s,%s)
    """
    for kontraktsomraade in data['kontraktsområder']:
        values = (
            kontraktsomraade.get('id'),
            kontraktsomraade.get('nummer'),
            kontraktsomraade.get("navn"),
            lokasjon_id,
            vegobjekt_id
        )        
        mydb_cursor.execute(sql, values)
        
        mydb.commit()

    mydb_cursor.close()

def insert_vegobjekt_vegforvaltere(mydb_cursor, data,lokasjon_id,vegobjekt_id):

    mydb_cursor = mydb.cursor()

    sql = """
    INSERT INTO vegobjekt_vegforvaltere (
        enumid,
        vegforvalter,
        lokasjon_id,
        vegobjekt_id

    )
    VALUES (%s, %s,%s,%s)
    """
 
    for vegforvalter in data['vegforvaltere']:
        values = (
            vegforvalter.get('enumid'),
            vegforvalter.get('vegforvalter'),
            lokasjon_id,
            vegobjekt_id
        )        
        mydb_cursor.execute(sql, values)
        
        mydb.commit()

    mydb_cursor.close()

def insert_vegobjekt_adresser(mydb_cursor, data,lokasjon_id,vegobjekt_id):

    mydb_cursor = mydb.cursor()

    sql = """
    INSERT INTO vegobjekt_adresser (
        navn,
        adressekode,
        
        lokasjon_id,
        vegobjekt_id

    )
    VALUES (%s, %s,%s,%s)
    """
 
    for adresse in data['adresser']:
        values = (
            adresse.get('navn'),
            adresse.get('adressekode'),
            lokasjon_id,
            vegobjekt_id
        )        
        mydb_cursor.execute(sql, values)
        
        mydb.commit()

    mydb_cursor.close()


# mydb_cursor.execute(create_vegobjekt_adresser)
# print(mydb_cursor.fetchall())
def insert_vegobjekt_riksvegruter(mydb_cursor, data,lokasjon_id,vegobjekt_id):



    sql = """
    INSERT INTO vegobjekt_riksvegruter (
        enumid,
        riksvegrute,
        
        lokasjon_id,
        vegobjekt_id

    )
    VALUES (%s, %s,%s,%s)
    """
 
    for riksvegrute in data['riksvegruter']:
        values = (
            riksvegrute.get('enumid'),
            riksvegrute.get('riksvegrute'),
            lokasjon_id,
            vegobjekt_id
        )        
        mydb_cursor.execute(sql, values)

In [574]:

params = {
'inkluder':'egenskaper,lokasjon',
'srid':'5973',
'segmentering':'false',
'trafikantgruppe':'K',#kjørende
'fylke':50,
'endret_etter':'2018-01-01T12:13:01',
'antall':200,
'start':'1002101974:0'
}

jwt_token = 'eyJ0eXAiOiJKV1QiLCJraWQiOiJITUNDTDd0ei93dWZja3ArcGVldUN0bmpyVms9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIyMjA0OTEzOTExMyIsImN0cyI6Ik9BVVRIMl9TVEFURUxFU1NfR1JBTlQiLCJhdXRoX2xldmVsIjo0MCwiYXVkaXRUcmFja2luZ0lkIjoiNTQ4MzVlOGEtNmYzNi00ZTEwLWI1YWQtNDBlMDEzMjJiMTRlLTUwMjg4NTA5Iiwic3VibmFtZSI6IjIyMDQ5MTM5MTEzIiwiaXNzIjoiaHR0cHM6Ly93d3cudmVndmVzZW4ubm86NDQzL29wZW5hbS9vYXV0aDIvcmVhbG1zL3Jvb3QvcmVhbG1zL25vcmdlLm5vIiwidG9rZW5OYW1lIjoiYWNjZXNzX3Rva2VuIiwidG9rZW5fdHlwZSI6IkJlYXJlciIsImF1dGhHcmFudElkIjoiT19rWUllUE5iWldoNF96d0xDWDVEbS1oVG13Iiwibm9uY2UiOiJOV2p0SFNkV00wMjFGTVlzR0Vla1c1YVNBM0lnRDh1MCIsImF1ZCI6WyIzNzhhYzM5Yi0xODBkLTQzZWEtOWVjNC0zZjg1ODU1ZGQ5MDMiLCJodHRwczovL2FwaS52ZWd2ZXNlbi5ubyIsImh0dHBzOi8vd3d3LnZlZ3Zlc2VuLm5vOjQ0My9vcGVuYW0vb2F1dGgyL3JlYWxtcy9yb290L3JlYWxtcy9ub3JnZS5ubyJdLCJuYmYiOjE3NzM3OTAyMzYsImdyYW50X3R5cGUiOiJhdXRob3JpemF0aW9uX2NvZGUiLCJzY29wZSI6WyJvcGVuaWQiLCJzdnZwYXJ0bmVycHJvZmlsZSJdLCJhdXRoX3RpbWUiOjE3NzM3OTAyMzUsInJlYWxtIjoiL25vcmdlLm5vIiwiZXhwIjoxNzczODE5MDM2LCJpYXQiOjE3NzM3OTAyMzYsImV4cGlyZXNfaW4iOjI4ODAwLCJqdGkiOiJMc0lrVFFabjBGTi1yNURqcTZEV3ZreFdCcWMiLCJhY3IiOiJMZXZlbDQiLCJuYW1lIjoiRk5SIGRldGVjdGVkIiwiZ2l2ZW5fbmFtZSI6IkZOUiBkZXRlY3RlZCIsImZhbWlseV9uYW1lIjoiRk5SIGRldGVjdGVkIiwibWF5X2FjdCI6eyJjbGllbnRfaWQiOlsiT0F1dGgyX0FQSUdXX1Rva2VuVHJhbnMiLCJPQXV0aDJfaWFtaWRlbnRpdHlicmlkZ2UiXX19.g718k1bKoDkX6f_yXtLqDG8CEtrw0tmzFVf0MWu6T2YkUAiqqt5ZpAGZ0rLtHpJnZDogTENVLYqpVxN70NTqyuqqfcQ2fQZrhm2LX_M4QpDupQ36C3iNspBHhf-5sbUSgU8fp6VhJy_AM_aTs6lhkzR3WyZcleNMkJwpkjMIzzbEbgQNAp8ErNiECpKexz3YdtPteXCkXaQ0ubgxLQPycJ3_OR1wpr5h8cQBqCQN1UuztHvRCddlMNPKDHSeJLpQpzNwjiUfuyHlO-azmSbUW-mv3cOzowtlNTEx9chSdXYH2PkWb8nlIZyFSFLlawWH6jn6jBfzn2lG57g77y8kFggedg57dfB2PiEOssmP6HeyRYX2LCUgQQnkOUqhvWov-c02YEbtsd3vhdOPR3oqefHe5CKQiOEwF7E8lXyqNZa9_6b9CXcosQzAVi5_ZlJAlKxDG810sqkxsYfa8pxyOSHz8kMoOvxqeVtg4aFV534aUh7_M5c5yTh2K6wX8AxR'
headers = {
 'Authorization': f'Bearer {jwt_token}',
 'X-Client': 'vj_case'
}




objekter_total = []


keeping_it_200 = True
count = 0 
while keeping_it_200:
    
    
    with requests.get("https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915",params = params, headers = headers) as response:
         resp_json = response.json()

    objekter_total += resp_json['objekter']

    mydb_cursor = mydb.cursor()
    
    for objekt in resp_json['objekter']:
        vegobjekt_id = objekt['id']

        try:
            insert_vegobjekt(mydb_cursor,objekt)
        
            insert_vegobjekt_egenskap(mydb_cursor, objekt['egenskaper'],vegobjekt_id)
        
            insert_vegobjekt_lokasjon(mydb_cursor, objekt['lokasjon'],vegobjekt_id)
            
        except:
            mydb.rollback()
            keeping_it_200 = False
            
            break

    mydb_cursor.commit()
    mydb_cursor.close()

    if keeping_it_200:
        params['start'] = resp_json['metadata']['neste']['start']
    
    if count %100 ==0:
        with open(f'vegobjekter_915_count_{count*200}.json', 'w') as f:
            json.dump(objekter, f)
    if count %50==0:
        print(count)
    
    keeping_it_200 = resp_json['metadata']['returnert']==200
    
    count += 1

0
50
100
150
200
250
300
350
400

KeyError: 'strekning'

In [19]:
create_hendelse = """CREATE TABLE hendelse (
                            id SERIAL PRIMARY KEY,
                            veglenkesekvensid BIGINT REFERENCES vegobjekt_stedfesting(veglenkesekvensid),
                            relativ_posisjon DOUBLE,
                            vegvedlikehold VARCHAR(25),
                            rand_float DOUBLE,
                            year int
                        );"""

mydb_cursor.execute(create_hendelse)


mydb_cursor.fetchall()



def dataframe_to_mysql(mydb, df):

    mydb_cursor = mydb.cursor()

    columns = ", ".join(df.columns)

    # Build placeholders for prepared statement
    strings_format = ", ".join(["%s"] * len(df.columns))

    sql = f"""INSERT INTO hendelse ({columns}) 
    VALUES ({strings_format})"""
    
    for i, row in df.iterrows():
        mydb_cursor.execute(sql, tuple(row))


        
    mydb.commit()
    mydb_cursor.close()


import pandas as pd
dat = pd.read_csv('hendelser 2.csv')

try:
    dataframe_to_mysql(mydb,dat)
except Exception as e:
    mydb.rollback()

In [41]:
# mydb_cursor = mydb.cursor()
mydb_cursor.fetchall()

query ="""SELECT hendelse.id, hendelse.veglenkesekvensid,relativ_posisjon, ((vegobjekt_stedfesting.sluttposisjon-vegobjekt_stedfesting.startposisjon)*relativ_posisjon) as absolutt_posisjon,
vegobjekt_stedfesting.startposisjon, vegobjekt_stedfesting.sluttposisjon, vegvedlikehold,rand_float,year, vegobjekt_stedfesting.vegobjekt_id, vegobjekt_stedfesting.lokasjon_id
from hendelse 
inner join vegobjekt_stedfesting
ON hendelse.veglenkesekvensid=vegobjekt_stedfesting.veglenkesekvensid 
"""
# mydb_cursor.fetchall()

In [42]:

df = pd.read_sql(query, mydb)
df

/tmp/ipykernel_5426/3706067849.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, mydb)

,id,veglenkesekvensid,relativ_posisjon,absolutt_posisjon,startposisjon,sluttposisjon,vegvedlikehold,rand_float,year,vegobjekt_id,lokasjon_id
0,850,578680,0.673304,0.372851,0.000000,0.553762,vegarbeid,0.000097,2023,1002102353,16
1,850,578680,0.673304,0.300454,0.553762,1.000000,vegarbeid,0.000097,2023,1002102364,21
2,3012,578178,0.846206,0.413887,0.000000,0.489109,vegarbeid,0.000026,2022,1002104439,37
3,3012,578178,0.846206,0.432319,0.489109,1.000000,vegarbeid,0.000026,2022,1002104440,38
4,1471,578183,0.684597,0.684597,0.000000,1.000000,vegarbeid,0.000076,2024,1002104862,48
...,...,...,...,...,...,...,...,...,...,...,...
2038,10282,72846,0.275662,0.152696,0.446075,1.000000,vegarbeid,0.000007,2022,1022257267,77182
2039,9041,72867,0.608899,0.365024,0.000000,0.599482,vegarbeid,0.000010,2022,1022423896,77471
2040,8020,72867,0.986070,0.591132,0.000000,0.599482,vegarbeid,0.000029,2024,1022423896,77471
2041,6019,1842156,0.158969,0.158969,0.000000,1.000000,vegarbeid,0.000049,2024,1025845824,80729
2042,8337,72447,0.834615,0.005769,0.993088,1.000000,vegarbeid,0.000075,2022,1026139913,81194

In [18]:
placeholders = ", ".join(["%s"] * len(dat.columns))
placeholders

'%s, %s, %s, %s, %s'

In [ ]:
mydb = get_connector("case2")
# mydb = get_connector("case2")
mydb_cursor = mydb.cursor()

In [11]:
mydb_cursor.execute(" select distinct count(veglenkesekvensid) from vegobjekt_stedfesting")
print(mydb_cursor.fetchall())

mydb_cursor.execute(" select count(veglenkesekvensid) from vegobjekt_stedfesting")
print(mydb_cursor.fetchall())

[(96672,)]
[(96672,)]

In [16]:

dat['relativ_posisjon'].min()

np.float64(0.0)

In [575]:

mydb_cursor = mydb.cursor()

# mydb_cursor.execute("""Select * from hendelse
# inner join  vegobjekt_vegsegment on vegobjekt_vegsegment.veglenkesekvensid = hendelse.veglenkesekvensid limit 10""")

query = """Select * from hendelse
inner join  vegobjekt_vegsegment on vegobjekt_vegsegment.veglenkesekvensid = hendelse.veglenkesekvensid  
WHERE hendelse.relativ_posisjon BETWEEN  vegobjekt_vegsegment.startposisjon AND vegobjekt_vegsegment.sluttposisjon
limit 10"""

91

5
5
5
5
5
5
5
5
5
5

10

{'id': 1026878971,
 'href': 'https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915/1026878971',
 'egenskaper': [{'id': 11277,
   'navn': 'Vegnummer',
   'verdi': 97623,
   'egenskapstype': 'Heltall'},
  {'id': 11278,
   'navn': 'Fase',
   'verdi': 'Eksisterende',
   'enum_id': 19032,
   'egenskapstype': 'Tekstenum'},
  {'id': 11276,
   'navn': 'Vegkategori',
   'verdi': 'Privat veg',
   'enum_id': 19028,
   'egenskapstype': 'Tekstenum'}],
 'lokasjon': {'kommuner': [5021],
  'fylker': [50],
  'adresser': [{'navn': 'Kjerkvegen', 'adressekode': 2445}],
  'vegsystemreferanser': [{'vegsystem': {'vegkategori': 'P',
     'fase': 'V',
     'nummer': 97623},
    'strekning': {'strekning': 1,
     'delstrekning': 1,
     'arm': False,
     'adskilte_løp': 'Nei',
     'trafikantgruppe': 'K',
     'retning': 'MED',
     'fra_meter': 0.0,
     'til_meter': 474.049},
    'metrertLokasjon': {'retning': 'MED'},
    'kortform': 'PV97623 S1D1 m0-474'}],
  'stedfestinger': [{'type': 'Linje',
    'veglenkesekvensid': 4064984,
    'startposisjon': 0.0,
    'sluttposisjon': 1.0,
    'retning': 'MED',
    'kjørefelt': [],
    'kortform': '0.0-1.0@4064984'}],
  'geometri': {'wkt': 'LINESTRING Z (226136.224 6955120.989 1128.814,226099.858 6955135.442 1135.761,226017.953 6955165.901 1146.012,225963.682 6955186.078 1157.923,225920.182 6955202.583 1169.808,225898.486 6955211.422 1174.12,225857.778 6955222.925 1179.16,225837.68 6955229.838 1182.071,225791.199 6955239.806 1185.853,225773.738 6955243.213 1187.445,225730.734 6955255.523 1190.196,225711.839 6955262.62 1192.39,225700.922 6955267.036 1193.594,225693.007 6955270.668 1194.909)',
   'srid': 5973},
  'lengde': 474.049}}

In [592]:
objekt = resp_json['objekter'][64]
for objekt in resp_json['objekter'][92:]:
    vegobjekt_id = objekt['id']
    
    insert_vegobjekt(mydb,objekt)
    
    insert_vegobjekt_egenskap(mydb, objekt['egenskaper'],vegobjekt_id)
    
    insert_vegobjekt_lokasjon(mydb, objekt['lokasjon'],vegobjekt_id)
    # break

In [589]:
objekt

{'id': 1026883588,
 'href': 'https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915/1026883588',
 'egenskaper': [{'id': 11277,
   'navn': 'Vegnummer',
   'verdi': 1093,
   'egenskapstype': 'Heltall'},
  {'id': 11278,
   'navn': 'Fase',
   'verdi': 'Eksisterende',
   'enum_id': 19032,
   'egenskapstype': 'Tekstenum'},
  {'id': 11276,
   'navn': 'Vegkategori',
   'verdi': 'Kommunal veg',
   'enum_id': 19027,
   'egenskapstype': 'Tekstenum'}],
 'lokasjon': {'kommuner': [5061],
  'fylker': [50],
  'adresser': [{'navn': 'Seljebrekka', 'adressekode': 1093}],
  'vegsystemreferanser': [{'vegsystem': {'vegkategori': 'K',
     'fase': 'V',
     'nummer': 1093},
    'strekning': {'strekning': 1,
     'delstrekning': 1,
     'arm': False,
     'adskilte_løp': 'Nei',
     'trafikantgruppe': 'K',
     'retning': 'MED',
     'fra_meter': 0.0,
     'til_meter': 7.905},
    'metrertLokasjon': {'retning': 'MED'},
    'kortform': 'KV1093 S1D1 m0-8'},
   {'vegsystem': {'vegkategori': 'K', 'fase': 'V', 'nummer': 1093},
    'strekning': {'strekning': 1,
     'delstrekning': 1,
     'arm': False,
     'adskilte_løp': 'Nei',
     'trafikantgruppe': 'K',
     'retning': 'MED',
     'fra_meter': 239.918,
     'til_meter': 555.413},
    'metrertLokasjon': {'retning': 'MED'},
    'kortform': 'KV1093 S1D1 m240-555'},
   {'vegsystem': {'vegkategori': 'K', 'fase': 'V', 'nummer': 1093},
    'kortform': 'KV1093'}],
  'stedfestinger': [{'type': 'Linje',
    'veglenkesekvensid': 3021290,
    'startposisjon': 0.0,
    'sluttposisjon': 1.0,
    'retning': 'MED',
    'kjørefelt': [],
    'kortform': '0.0-1.0@3021290'},
   {'type': 'Linje',
    'veglenkesekvensid': 3021301,
    'startposisjon': 0.0,
    'sluttposisjon': 1.0,
    'retning': 'MED',
    'kjørefelt': [],
    'kortform': '0.0-1.0@3021301'}],
  'geometri': {'wkt': 'LINESTRING Z (207690.43 7004377.02 150.538,207698.16 7004378.67 150.428,207704.87 7004377.851 150.438,207709.23 7004376.34 150.578,207712.94 7004374.9 150.868,207716.4 7004372.55 151.028,207719.59 7004369.76 151.548,207724.23 7004363.7 152.538,207729.33 7004355.92 153.548,207732.66 7004350.77 154.138,207736.51 7004345.5 154.958,207740.54 7004340.81 155.568,207745.74 7004336.16 156.258,207751.56 7004331.19 157.148,207757.17 7004327.74 157.938,207763.81 7004324.17 158.918,207772.88 7004320.22 159.968,207782.91 7004316.48 161.088,207793.16 7004313.1 162.138,207803.58 7004310.16 163.508,207817.59 7004306.57 164.848,207827.94 7004304.6 166.208,207835.59 7004303.09 167.108,207845.54 7004302.07 167.958,207854.15 7004301.15 168.918,207870.9 7004299.42 170.898,207879.73 7004299.29 171.778,207890.27 7004299.69 173.088,207897.17 7004300.59 173.858,207902.54 7004301.83 174.588,207911.91 7004304.91 175.248,207920.09 7004307.24 176.368,207928.9 7004309.29 177.138,207934.51 7004310.25 177.528,207940.48 7004310.89 177.998,207951.12 7004311.42 178.278,207958.18 7004311.11 178.438,207967.48 7004309.67 178.608,207979.7 7004306.46 179.148,207991.05 7004303.18 179.168,208006.54 7004298.12 179.208,208019.13 7004294.12 179.338,208039.27 7004287.33 179.728,208055.19 7004282.42 179.748,208071.78 7004276.99 179.968,208087.5 7004272.08 180.288,208105.61 7004266.38 180.198,208122.64 7004260.98 180.318,208142.96 7004254.23 180.678,208158.43 7004249.79 180.878,208176.93 7004243.78 180.898,208189.62 7004239.42 181.218,208195.63 7004237.54 181.568,208204.72 7004234.07 181.458)',
   'srid': 5973},
  'lengde': 555.413}}

In [104]:
# resp_json

import json

objekter = []
with requests.get("https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915",params = params, headers = headers) as response:
    resp_json = response.json()

objekter= resp_json['objekter']

# count = 1
# count += 1

while resp_json['metadata']['returnert']==200:
    params['start'] = resp_json['metadata']['neste']['start']
    
    with requests.get("https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915",params = params, headers = headers) as response:
        resp_json = response.json()
    count += 1

    objekter += resp_json['objekter']

    if count %100 ==0:
        with open(f'vegobjekter_915_count_{count*200}.json', 'w') as f:
            json.dump(objekter, f)


with open(f'vegobjekter_915_count_{len(objekter)}.json', 'w') as f:
    json.dump(objekter, f)

120
140
160
180
200
220
240
260
280
300
320
340
360
380
400

In [263]:
import mysql.connector



def get_connector()-> mysql.connector:
    try:
        mydb = mysql.connector.connect(
          host="localhost",
          user="case_user",
          password="password",
          database="case" # Optional: connect to a specific database directly
        )
        print("Connection successful!")
        return mydb
    except mysql.connector.Error as err:
        print(f"Error: {err}")
        return None

mydb = get_connector()
mydb_cursor = mydb.cursor()


# mydb_cursor.execute("CREATE DATABASE case")

Connection successful!

In [131]:


with open('vegobjekter_915_count_81482.json', 'r') as file:
    data = json.load(file)

[('case',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sys',)]

In [160]:
# mydb_cursor.execute(create_vegobjekt)
# mydb_cursor_ = mydb_cursor.fetchall()
# mydb_cursor_ =mydb_cursor.execute("SHOW TABLES")

AttributeError: 'NoneType' object has no attribute 'fetchall'

In [163]:
mydb_cursor_ = mydb_cursor.fetchall()
mydb_cursor_

[('vegobjekt',)]

In [265]:
create_databases_again = False

if create_databases_again:
    create_vegobjekt = """CREATE TABLE vegobjekt (
                        id BIGINT PRIMARY KEY,
                        href TEXT,
                        type_id INT,
                        type_navn VARCHAR(100),
                        versjon INT,
                        startdato DATE,
                        sist_modifisert TIMESTAMP
                    );"""
    # mydb_cursor.execute(create_vegobjekt)
    print(mydb_cursor.fetchall())
    
    create_vegobjekt_egenskap = """CREATE TABLE vegobjekt_egenskap (
                                vegobjekt_id BIGINT ,
                            
                                egenskap_id INT,
                                navn VARCHAR(100),
                                verdi_text TEXT,
                                verdi_int INT,
                                enum_id INT,
                                egenskapstype VARCHAR(50),
                                
                                PRIMARY KEY (vegobjekt_id, egenskap_id),
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""
    # mydb_cursor.execute(create_vegobjekt_egenskap)
    print(mydb_cursor.fetchall())

    create_vegobjekt_lokasjon = """CREATE TABLE vegobjekt_lokasjon (
                                id SERIAL PRIMARY KEY,
                                vegobjekt_id BIGINT,
                                lengde DOUBLE PRECISION,
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                            );"""
    
    # mydb_cursor.execute(create_vegobjekt_lokasjon)
    print(mydb_cursor.fetchall())
    
    create_vegobjekt_kommune = """CREATE TABLE vegobjekt_lokasjon_kommuner (
                                    lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                    kommune INT,
                                    vegobjekt_id BIGINT,
                                    PRIMARY KEY (lokasjon_id, kommune),
                                    FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                                );"""
    
    
    mydb_cursor.execute(create_vegobjekt_kommune)
    print(mydb_cursor.fetchall())

    create_vegobjekt_vegsystemreferanse = """CREATE TABLE vegobjekt_vegsystemreferanse (
                                id SERIAL PRIMARY KEY,
                                lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                            
                                vegkategori CHAR(1),
                                fase CHAR(1),
                                vegnummer INT,
                            
                                strekning INT,
                                delstrekning INT,
                                arm BOOLEAN,
                                adskilte_lop VARCHAR(10),
                                trafikantgruppe CHAR(1),
                                retning VARCHAR(10),
                                fra_meter DOUBLE PRECISION,
                                til_meter DOUBLE PRECISION,
                            
                                metrert_retning VARCHAR(10),
                            
                                kortform VARCHAR(50),
                                vegobjekt_id BIGINT,
                                FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                                
                            );"""
    mydb_cursor.execute(create_vegobjekt_vegsystemreferanse)
    print(mydb_cursor.fetchall())

    create_vegobjekt_stedfesting = """CREATE TABLE vegobjekt_stedfesting (
                                    id SERIAL PRIMARY KEY,
                                    lokasjon_id INT REFERENCES vegobjekt_lokasjon(id),
                                
                                    type VARCHAR(20),
                                    veglenkesekvensid BIGINT,
                                    startposisjon DOUBLE PRECISION,
                                    sluttposisjon DOUBLE PRECISION,
                                    retning VARCHAR(10),
                                    kortform VARCHAR(50),
                                    vegobjekt_id BIGINT,
                                    FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                                );"""
    mydb_cursor.execute(create_vegobjekt_stedfesting)
    print(mydb_cursor.fetchall())

    create_vegobjekt_vegsegment = """CREATE TABLE vegobjekt_vegsegment (
                                    id SERIAL PRIMARY KEY,
                                    vegobjekt_id BIGINT,
                                
                                    veglenkesekvensid BIGINT,
                                    startposisjon DOUBLE PRECISION,
                                    sluttposisjon DOUBLE PRECISION,
                                    lengde DOUBLE PRECISION,
                                    retning VARCHAR(10),
                                
                                    veglenketype VARCHAR(50),
                                    detaljnivaa VARCHAR(100),
                                    typeveg VARCHAR(100),
                                    typeveg_sosi VARCHAR(100),
                                
                                    startdato DATE,
                                
                                    kommune INT,
                                    fylke INT,
                                    FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
    
                                );"""
    
    
    mydb_cursor.execute(create_vegobjekt_vegsegment)
    print(mydb_cursor.fetchall())


    vegobjekt_vegsegment_vegsystemreferanse = """CREATE TABLE vegobjekt_vegsegment_vegsystemreferanse (
                                    vegsegment_id INT PRIMARY KEY REFERENCES vegobjekt_vegsegment(id),
                                
                                    vegkategori CHAR(1),
                                    fase CHAR(1),
                                    vegnummer INT,
                                
                                    strekning INT,
                                    delstrekning INT,
                                    arm BOOLEAN,
                                    adskilte_lop VARCHAR(10),
                                    trafikantgruppe CHAR(1),
                                    retning VARCHAR(10),
                                    fra_meter DOUBLE PRECISION,
                                    til_meter DOUBLE PRECISION,
                                
                                    kortform VARCHAR(50),
                                    vegobjekt_id BIGINT,
                                    FOREIGN KEY (vegobjekt_id) REFERENCES vegobjekt(id)
                                );"""
        
    mydb_cursor.execute(vegobjekt_vegsegment_vegsystemreferanse)
    print(mydb_cursor.fetchall())

mydb_cursor.execute("SHOW TABLES")
print(mydb_cursor.fetchall())

[('vegobjekt',), ('vegobjekt_egenskap',), ('vegobjekt_lokasjon',), ('vegobjekt_lokasjon_kommune',), ('vegobjekt_stedfesting',), ('vegobjekt_vegsegment',), ('vegobjekt_vegsegment_vegsystemreferanse',), ('vegobjekt_vegsystemreferanse',)]

In [210]:
mydb_cursor.execute('SELECT LAST_INSERT_ID()')
print(mydb_cursor.fetchone()[0])

1

In [189]:
objekter[0]['metadata']

{'type': {'id': 915, 'navn': 'Vegsystem'},
 'versjon': 1,
 'startdato': '1950-01-01',
 'sist_modifisert': '2025-05-02T15:18:34Z'}

In [324]:
from tqdm import tqdm

In [348]:
objekter[0]['metadata']
count = 9
for objekt in tqdm(objekter[9:]):
    
    vegobjekt_id = objekt['id']
    
    insert_vegobjekt(mydb, objekt)
    for egenskaper in objekt['egenskaper']:
        insert_vegobjekt_egenskap(mydb, egenskaper,vegobjekt_id)

    insert_vegobjekt_lokasjon(mydb,objekt['lokasjon'],vegobjekt_id)

    insert_vegobjekt_vegsegment(mydb,objekt['vegsegmenter'],vegobjekt_id)

    count+=1
    # break

100%|███████████████████████████████████| 81473/81473 [3:52:36<00:00,  5.84it/s]

In [352]:
create_vegobjekt_egenskap = """CREATE TABLE hendelse (
                            id SERIAL PRIMARY KEY,
                            veglenkesekvensid BIGINT REFERENCES vegobjekt_vegsegment(veglenkesekvensid),
                            relativ_posisjon DOUBLE PRECISION,
                            vegvedlikehold VARCHAR(25),
                            rand_float DOUBLE PRECISION,
                            year int
                        );"""

mydb_cursor.execute(create_vegobjekt_egenskap)


mydb_cursor.fetchall()


dat = pd.read_csv('hendelser 2.csv')



def dataframe_to_mysql(mydb, df):

    mydb_cursor = mydb.cursor()

    # Build column list
    columns = ", ".join(df.columns)

    # Build placeholders for prepared statement
    placeholders = ", ".join(["%s"] * len(df.columns))

    sql = f"""INSERT INTO hendelse (
    veglenkesekvensid,
    relativ_posisjon,
    vegvedlikehold,
    rand_float,
    year) 
    VALUES (%s,%s,%s,%s,%s)"""

    for i, row in df.iterrows():
        mydb_cursor.execute(sql, tuple(row))

    mydb.commit()
    mydb_cursor.close()


dataframe_to_mysql(mydb,dat)

[]

In [399]:
objekter[0]
dat

       veglenkesekvensid  relativ_posisjon vegvedlikehold  rand_float  year
0                   1507          0.073856      vegarbeid    0.000021  2022
1                 885358          0.336582      vegarbeid    0.000027  2023
2                 705244          0.591494      vegarbeid    0.000019  2024
3                 444326          0.355883      vegarbeid    0.000010  2022
4                 625212          0.162475      vegarbeid    0.000047  2024
...                  ...               ...            ...         ...   ...
10816            1125847          0.480906      vegarbeid    0.000076  2022
10817             121370          0.274469      vegarbeid    0.000049  2022
10818            1060139          0.070170      vegarbeid    0.000017  2024
10819             885373          0.374164      vegarbeid    0.000061  2022
10820             971731          0.773502      vegarbeid    0.000074  2024

[10821 rows x 5 columns]

In [389]:

mydb_cursor = mydb.cursor()

# mydb_cursor.execute("""Select * from hendelse
# inner join  vegobjekt_vegsegment on vegobjekt_vegsegment.veglenkesekvensid = hendelse.veglenkesekvensid limit 10""")

query = """Select * from hendelse
inner join  vegobjekt_vegsegment on vegobjekt_vegsegment.veglenkesekvensid = hendelse.veglenkesekvensid  
WHERE hendelse.relativ_posisjon BETWEEN  vegobjekt_vegsegment.startposisjon AND vegobjekt_vegsegment.sluttposisjon
limit 10"""

In [396]:
df = pd.read_sql("select * from vegobjekt_stedfesting where vegobjekt_id = 1002102314", mydb)
df

/tmp/ipykernel_15316/2205198203.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("select * from vegobjekt_stedfesting where vegobjekt_id= 1002102314", mydb)

,id,lokasjon_id,type,veglenkesekvensid,startposisjon,sluttposisjon,retning,kortform,vegobjekt_id
0,6,7,Linje,72299,0.181200,0.495062,MED,0.1811995-0.49506187@72299,1002102314
1,7,7,Linje,72299,0.559134,1.000000,MED,0.55913388-1.0@72299,1002102314
2,8,7,Linje,72832,0.000000,0.146557,MED,0.0-0.14655692@72832,1002102314
3,9,7,Linje,2801057,0.000000,1.000000,MED,0.0-1.0@2801057,1002102314
4,10,7,Linje,2801073,0.000000,1.000000,MED,0.0-1.0@2801073,1002102314
5,11,7,Linje,3113818,0.000000,1.000000,MED,0.0-1.0@3113818,1002102314
6,12,7,Linje,3113819,0.000000,1.000000,MED,0.0-1.0@3113819,1002102314

In [390]:
df = pd.read_sql(query, mydb)
df

/tmp/ipykernel_15316/1018605566.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, mydb)

,id,veglenkesekvensid,relativ_posisjon,vegvedlikehold,rand_float,year,id,vegobjekt_id,veglenkesekvensid,startposisjon,sluttposisjon,lengde,retning,veglenketype,detaljnivaa,typeveg,typeveg_sosi,startdato,kommune,fylke
0,850,578680,0.673304,vegarbeid,0.000097,2023,53,1002102364,578680,0.553762,1.000000,4452.596,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5060,50
1,3012,578178,0.846206,vegarbeid,0.000026,2022,110,1002104440,578178,0.489109,1.000000,5095.617,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5006,50
2,1471,578183,0.684597,vegarbeid,0.000076,2024,298,1002104862,578183,0.000432,0.712649,6593.731,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5042,50
3,2173,578185,0.599989,vegarbeid,0.000082,2024,305,1002104864,578185,0.358539,1.000000,6344.019,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5042,50
4,369,578219,0.015413,vegarbeid,0.000005,2022,395,1002110473,578219,0.000000,0.989201,6859.578,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5043,50
5,1155,578202,0.243069,vegarbeid,0.000055,2024,449,1002111192,578202,0.000000,1.000000,5920.964,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5007,50
6,2051,578206,0.060347,vegarbeid,0.000090,2022,460,1002111197,578206,0.000000,0.294830,2266.730,MED,HOVED,Vegtrase og kjørebane,Bilferje,bilferje,2026-01-23,5007,50
7,812,578676,0.380081,vegarbeid,0.000044,2023,494,1002111215,578676,0.000000,0.581927,5811.055,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5060,50
8,3311,578224,0.713385,vegarbeid,0.000036,2023,516,1002111404,578224,0.000000,1.000000,9000.000,MED,HOVED,Vegtrase og kjørebane,Bilferje,bilferje,2026-01-23,5037,50
9,2092,72818,0.738694,vegarbeid,0.000054,2023,566,1002118144,72818,0.616687,1.000000,3785.099,MED,HOVED,Vegtrase og kjørebane,Enkel bilveg,enkelBilveg,2026-01-23,5027,50

In [368]:
dat
for a, row in dat.iterrows():
    print(a)
    print(tuple(row))
    break

0
(1507, 0.07385555, 'vegarbeid', 2.09992581103e-05, 2022)

In [199]:

def insert_hendelse(mydb, data):

    mydb_cursor = mydb.cursor()
    # mydb_cursor.execute('SELECT LAST_INSERT_ID()')
    # last_id = mydb_cursor.fetchone()[0]
    vegobjekt_vegsegment_id = []
    sql = """
    INSERT INTO hendelse (
                            veglenkesekvensid,
                            relativ_posisjon,
                            vegvedlikehold,
                            rand_float,
                            year 
        
    )
    VALUES (%s, %s,%s,%s,%s)
    """
    
    for veg in data:
        values = (
            vegobjekt_id,
            veg.get('veglenkesekvensid'),
            veg.get("startposisjon"),
            veg.get('sluttposisjon'),
            veg.get('lengde'),
            veg.get('retning'),
            veg.get('veglenkeType'),
            veg.get('detaljnivå'),
            veg.get('typeVeg'),
            veg.get('typeVeg_sosi'),
            veg.get('startdato'),
            veg.get('kommune'),
            veg.get('fylke')

        )

    
        mydb_cursor.execute(sql, values)
        
        mydb.commit()
    
        mydb_cursor.execute('SELECT LAST_INSERT_ID()')
        last_id = mydb_cursor.fetchone()[0]
        vegobjekt_vegsegment_id.append(last_id)
    
    mydb_cursor.close() 
    insert_vegobjekt_vegsegment_vegsystemreferanse(mydb,data,vegobjekt_vegsegment_id,vegobjekt_id)

SyntaxError: invalid syntax (313909315.py, line 1)

In [123]:
objects = []

for o in objekter:
    objects += o

In [130]:
len(objects)
objekter = objects
with open(f'vegobjekter_915_count_{len(objekter)}.json', 'w') as f:
    json.dump(objekter, f)

In [397]:
objekter[0]

{'id': 1002101974,
 'href': 'https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915/1002101974',
 'metadata': {'type': {'id': 915, 'navn': 'Vegsystem'},
  'versjon': 1,
  'startdato': '1950-01-01',
  'sist_modifisert': '2025-05-02T15:18:34Z'},
 'egenskaper': [{'id': 11277,
   'navn': 'Vegnummer',
   'verdi': 99999,
   'egenskapstype': 'Heltall'},
  {'id': 11278,
   'navn': 'Fase',
   'verdi': 'Fiktiv',
   'enum_id': 19090,
   'egenskapstype': 'Tekstenum'},
  {'id': 11276,
   'navn': 'Vegkategori',
   'verdi': 'Europaveg',
   'enum_id': 19024,
   'egenskapstype': 'Tekstenum'}],
 'geometri': {'wkt': 'LINESTRING Z (274013 7010756 -999999,274113 7010756 -999999)',
  'srid': 5973,
  'egengeometri': False},
 'lokasjon': {'kommuner': [5028],
  'fylker': [50],
  'vegsystemreferanser': [{'vegsystem': {'vegkategori': 'E',
     'fase': 'F',
     'nummer': 99999},
    'strekning': {'strekning': 30,
     'delstrekning': 1,
     'arm': False,
     'adskilte_løp': 'Nei',
     'trafikantgruppe': 'K',
     'retning': 'MED',
     'fra_meter': 0.0,
     'til_meter': 100.0},
    'metrertLokasjon': {'retning': 'MED'},
    'kortform': 'EF99999 S30D1 m0-100'}],
  'stedfestinger': [{'type': 'Linje',
    'veglenkesekvensid': 72138,
    'startposisjon': 0.0,
    'sluttposisjon': 1.0,
    'retning': 'MED',
    'kjørefelt': [],
    'kortform': '0.0-1.0@72138'}],
  'geometri': {'wkt': 'LINESTRING Z (274013 7010756 -999999,274113 7010756 -999999)',
   'srid': 5973},
  'lengde': 100.0},
 'relasjoner': {},
 'vegsegmenter': [{'veglenkesekvensid': 72138,
   'startposisjon': 0.0,
   'sluttposisjon': 1.0,
   'lengde': 100.0,
   'retning': 'MED',
   'feltoversikt': ['1', '2'],
   'veglenkeType': 'HOVED',
   'detaljnivå': 'Vegtrase og kjørebane',
   'typeVeg': 'Enkel bilveg',
   'typeVeg_sosi': 'enkelBilveg',
   'startdato': '2019-11-07',
   'geometri': {'wkt': 'LINESTRING Z (274013 7010756 -999999,274113 7010756 -999999)',
    'srid': 5973},
   'kommune': 5028,
   'fylke': 50,
   'vegsystemreferanse': {'vegsystem': {'vegkategori': 'E',
     'fase': 'F',
     'nummer': 99999},
    'strekning': {'strekning': 30,
     'delstrekning': 1,
     'arm': False,
     'adskilte_løp': 'Nei',
     'trafikantgruppe': 'K',
     'retning': 'MED',
     'fra_meter': 0.0,
     'til_meter': 100.0},
    'kortform': 'EF99999 S30D1 m0-100'}}]}

In [83]:
print(resp_json['objekter'][0]['id'])
print(resp_json['objekter'][0]['href'])
print(resp_json['objekter'][0]['metadata'])
print(resp_json['objekter'][0].keys())
print(resp_json['objekter'][0]['egenskaper'])
print(resp_json['objekter'][-1]['id'])
print(resp_json['metadata'])

1002101974
https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915/1002101974
{'type': {'id': 915, 'navn': 'Vegsystem'}, 'versjon': 1, 'startdato': '1950-01-01', 'sist_modifisert': '2025-05-02T15:18:34Z'}
dict_keys(['id', 'href', 'metadata', 'egenskaper', 'geometri', 'lokasjon', 'relasjoner', 'vegsegmenter'])
[{'id': 11277, 'navn': 'Vegnummer', 'verdi': 99999, 'egenskapstype': 'Heltall'}, {'id': 11278, 'navn': 'Fase', 'verdi': 'Fiktiv', 'enum_id': 19090, 'egenskapstype': 'Tekstenum'}, {'id': 11276, 'navn': 'Vegkategori', 'verdi': 'Europaveg', 'enum_id': 19024, 'egenskapstype': 'Tekstenum'}]
1002134526
{'returnert': 200, 'sidestørrelse': 200, 'neste': {'start': '1002134526:1', 'href': 'https://nvdbapiles.atlas.vegvesen.no/vegobjekter/915?inkluder=alle&srid=5973&segmentering=false&trafikantgruppe=K&fylke=50&endret_etter=2018-01-01T12:13:01&start=1002134526:1&antall=200'}}

In [72]:
resp_json['objekter'][3]['lokasjon']

{'kommuner': [5028],
 'fylker': [50],
 'vegsystemreferanser': [{'vegsystem': {'vegkategori': 'F',
    'fase': 'F',
    'nummer': 99999},
   'strekning': {'strekning': 30,
    'delstrekning': 1,
    'arm': False,
    'adskilte_løp': 'Nei',
    'trafikantgruppe': 'K',
    'retning': 'MED',
    'fra_meter': 0.0,
    'til_meter': 100.0},
   'metrertLokasjon': {'retning': 'MED'},
   'kortform': 'FF99999 S30D1 m0-100'}],
 'stedfestinger': [{'type': 'Linje',
   'veglenkesekvensid': 72140,
   'startposisjon': 0.0,
   'sluttposisjon': 1.0,
   'retning': 'MED',
   'kjørefelt': [],
   'kortform': '0.0-1.0@72140'}],
 'geometri': {'wkt': 'LINESTRING Z (274013 7010656 -999999,274113 7010656 -999999)',
  'srid': 5973},
 'lengde': 100.0}

In [19]:
resp = requests.get('https://nvdbapiles.atlas.vegvesen.no/vegobjekter/api/v4/vegobjekt?id=85773305&inkluder=metadata&inkluder=lokasjon&inkluder=geometri',headers = headers)

In [20]:
resp.text

resp_json['objekter'][0]['egenskaper']

'{"id":85773305,"href":"https://nvdbapiles.atlas.vegvesen.no/vegobjekter/96/85773305","metadata":{"type":{"id":96,"navn":"Skiltplate"},"versjon":1,"startdato":"2005-07-25","sist_modifisert":"2025-11-22T10:54:13Z"},"geometri":{"wkt":"POINT Z (269101.622 7035280.985 -999999)","srid":5973,"egengeometri":true},"lokasjon":{"kommuner":[5001],"fylker":[50],"kontraktsområder":[{"id":1004758086,"nummer":9401,"navn":"9401 Trondheim 2020-2025 (f.o.m. 01.09.2023)"},{"id":1007479425,"nummer":9451,"navn":"9451 Elektrokontrakt Trøndelag 2022-2026"},{"id":1019226085,"nummer":9405,"navn":"DK 9405 Trøndelag sør"},{"id":1019330755,"nummer":9481,"navn":"9481 Rekkverk Trøndelag og Møre og Romsdal 2023-2024"},{"id":1025260306,"nummer":9451,"navn":"9451 Elektrokontrakt Trøndelag 2026-2031"}],"riksvegruter":[{"enumid":20296,"riksvegrute":"Rute 6a: E6 Oslo - Trondheim"}],"vegforvaltere":[{"enumid":21771,"vegforvalter":"Statens vegvesen"}],"adresser":[{"navn":"Europaveg 6","adressekode":1666}],"vegsystemreferanser":[{"vegsystem":{"vegkategori":"E","fase":"V","nummer":6},"strekning":{"strekning":75,"delstrekning":1,"arm":false,"adskilte_løp":"Nei","trafikantgruppe":"K","retning":"MED","meter":191.72},"metrertLokasjon":{"retning":"MED","sideposisjon":"H"},"kortform":"EV6 S75D1 m192"}],"stedfestinger":[{"type":"Punkt","veglenkesekvensid":72810,"relativPosisjon":0.77755961,"retning":"MED","kjørefelt":[],"sideposisjon":"H","kortform":"0.77755961@72810"}],"geometri":{"wkt":"POINT Z (269091.091 7035280.378 133.776)","srid":5973}}}'

In [26]:
import mysql.connector

In [28]:
try:
    mydb = mysql.connector.connect(
      host="localhost",
      user="case_user",
      password="password",
      # database="mydatabase" # Optional: connect to a specific database directly
    )
    print("Connection successful!")
except mysql.connector.Error as err:
    print(f"Error: {err}")

Connection successful!

In [ ]:
CREATE TABLE nvdb_vegobjekt_egenskaper (
    id INT 
    navn VARCHAR(100) NOT NULL,
    verdi_text VARCHAR(255),
    verdi_int INT,
    enum_id INT,
    egenskapstype VARCHAR(50) NOT NULL
    PRIMARY KEY (order_id, id)
);

CREATE TABLE nvdb_egenskap (
    vegobjekt_id BIGINT,
    egenskap_id INT,
    navn VARCHAR(100),
    verdi_text VARCHAR(255),
    verdi_int INT,
    enum_id INT,
    egenskapstype VARCHAR(50),
    PRIMARY KEY (vegobjekt_id, egenskap_id)
    FOREIGN KEY (vegobjekt_id) REFERENCES Persons(vegobjekt_id)
);

In [ ]:
### lokasjon


CREATE TABLE nvdb_vegsystemreferanse (
    id AUTO_INCREMENT PRIMARY KEY,
    vegobjekt_id INT REFERENCES nvdb_vegobjekt(id),

    vegkategori CHAR(1),
    fase CHAR(1),
    vegnummer INT,

    strekning INT,
    delstrekning INT,
    arm BOOLEAN,
    adskilte_lop VARCHAR(10),
    trafikantgruppe CHAR(1),
    retning VARCHAR(10),
    fra_meter DOUBLE PRECISION,
    til_meter DOUBLE PRECISION,

    metrert_retning VARCHAR(10),

    kortform VARCHAR(50)
);

CREATE TABLE nvdb_stedfesting (
    id AUTO_INCREMENT PRIMARY KEY,
    vegobjekt_id INT REFERENCES nvdb_vegobjekt(id),

    type VARCHAR(20),
    veglenkesekvensid BIGINT,
    startposisjon DOUBLE PRECISION,
    sluttposisjon DOUBLE PRECISION,
    retning VARCHAR(10),
    kortform VARCHAR(50)
);



CREATE TABLE nvdb_vegobjekt_kommuner (
    vegobjekt_id INT REFERENCES nvdb_vegobjekt(id),
    kommune INT,
    PRIMARY KEY (vegobjekt_id, kommune)
);


CREATE TABLE nvdb_vegobjekt_fylker (
    vegobjekt_id INT REFERENCES nvdb_vegobjekt(id),
    fylke INT,
    PRIMARY KEY (vegobjekt_id, fylke)
);


CREATE TABLE nvdb_vegobjekt (
    id SERIAL PRIMARY KEY,
    lengde DOUBLE PRECISION
);

In [ ]:
[{'vegsystem': {'vegkategori': 'F', 'fase': 'F', 'nummer': 99999},
  'strekning': {'strekning': 30,
   'delstrekning': 1,
   'arm': False,
   'adskilte_løp': 'Nei',
   'trafikantgruppe': 'K',
   'retning': 'MED',
   'fra_meter': 0.0,
   'til_meter': 100.0},
  'metrertLokasjon': {'retning': 'MED'},
  'kortform': 'FF99999 S30D1 m0-100'}]

In [ ]:
mycursor = mydb.cursor()